### ISSUE TITLE
[其他] 微小的建议内容

### ISSUE THREAD

**Issue by Darknight123MC** [ET-Team/ET-Atiotus#12]
1.其实可以在1.16.5使用KubeJS，KubeJS在某些地方比CrT更加好用。
2.另一个是发现已经加入的大部分模组，在1.18.2都有，是否有想法升级？
3.高版本其实可以试试Roughly Enough Items。

**Comment by dong031001** [comment]
已经迁移至KJS。进度Q群建议你post你的QQ号
