### ISSUE TITLE
[其他]关于ETA的建议。

### ISSUE THREAD

**Issue by Hydrogen897** [ET-Team/ET-Atiotus#2]
首先是可以使用模组`CensoredASM`（前置为Mixinbooter）代替`VanillaFix`，前者包括了后者所有的功能并且优化了其他东西。

然后可以用`AE Additions - Extra Cells 2 Fork`模组（前置为`Shadowfact‘s Forgelin`）代替`Extra Cells 2`，前者优化了EC2的一部分东西。

JEE（即Just Enough Energistics）模组可以替换为Not Enough Energistics，后者优化了搜索等相关功能。

JEI可以替换成Had Enough Items，后者优化了搜索和大量物品渲染。
顺便将Just Enough Characters替换为Had Enough Characters，用于兼容HEI。

AE2可以替换成AE2 Unofficial Extended Life版本，后者在ET2内已经用到过。

（由于这部分我是直接在modlist.html里看的，所以原模组准不准确我不知道）

以及可以开仓库分支，例如expert和normal，这样可以对不同的PackMode的脚本进行模块式管理。

目前就这些。

**Comment by dong031001** [comment]
抱歉迟来的回复，整合整体迁移至1.16.5了，上述模组大多停留在1.12.2。
